// @generated by `tests/codegen.rs`, DO NOT EDIT BY HAND.
// Run `SNAPSHOTS=overwrite cargo test --test codegen` to regenerate.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(clippy::too_many_lines)]

use std::iter;

use itertools::Itertools;
use pacaptr::{
    config::Config,
    error::{Error, Result},
    pm::BoxPm,
    print::{println, prompt},
};

use super::{Operations, Pacaptr};

impl Pacaptr {
    /// Executes the job according to the flags received and the package manager
    /// detected.
    ///
    /// # Errors
    /// See [`Error`](pacaptr::error::Error) for a list of possible errors.
    #[allow(trivial_numeric_casts)]
    pub(super) async fn dispatch_from(&self, mut cfg: Config) -> Result<()> {
        // Collect options as a `String`, eg. `-S -y -u => "Suy"`.
        //
        // In `Pm` we ensure the Pacman methods are all named with flags in
        // ASCII order, eg. `Suy` instead of `Syu`. Then, in order to
        // stay coherent with Rust coding style the method name should be
        // `suy`.
        let mut options = String::new();
        match self.ops {
            Operations::Query { c, e, i, k, l, m, o, p, s, u, .. } => {
                options.push('Q');
                options.extend(iter::repeat_n('c', usize::from(c)));
                options.extend(iter::repeat_n('e', usize::from(e)));
                options.extend(iter::repeat_n('i', usize::from(i)));
                options.extend(iter::repeat_n('k', usize::from(k)));
                options.extend(iter::repeat_n('l', usize::from(l)));
                options.extend(iter::repeat_n('m', usize::from(m)));
                options.extend(iter::repeat_n('o', usize::from(o)));
                options.extend(iter::repeat_n('p', usize::from(p)));
                options.extend(iter::repeat_n('s', usize::from(s)));
                options.extend(iter::repeat_n('u', usize::from(u)));
            }
            Operations::Remove { p, n, s, .. } => {
                options.push('R');
                if p { cfg.dry_run = true; }
                options.extend(iter::repeat_n('n', usize::from(n)));
                options.extend(iter::repeat_n('s', usize::from(s)));
            }
            Operations::Sync { p, c, g, i, l, s, u, w, y, .. } => {
                options.push('S');
                if p { cfg.dry_run = true; }
                options.extend(iter::repeat_n('c', usize::from(c)));
                options.extend(iter::repeat_n('g', usize::from(g)));
                options.extend(iter::repeat_n('i', usize::from(i)));
                options.extend(iter::repeat_n('l', usize::from(l)));
                options.extend(iter::repeat_n('s', usize::from(s)));
                options.extend(iter::repeat_n('u', usize::from(u)));
                options.extend(iter::repeat_n('w', usize::from(w)));
                options.extend(iter::repeat_n('y', usize::from(y)));
            }
            Operations::Update { p, .. } => {
                options.push('U');
                if p { cfg.dry_run = true; }
            }
        }
        let options = String::from_iter(options.chars().sorted_unstable());

        // Ensure that the cursor is not hidden when `Ctrl-C` is used.
        // See: https://github.com/console-rs/dialoguer/issues/77#issuecomment-669986406
        if let Err(e) = ctrlc::set_handler(move || {
            let term = console::Term::stdout();
            _ = term.show_cursor();
        }) {
            println(&*prompt::INFO, e);
        }

        let pm = BoxPm::from(cfg);

        let kws = self.keywords.iter().map(AsRef::as_ref).collect_vec();
        let flags = self.extra_flags.iter().map(AsRef::as_ref).collect_vec();

        // Call the method indicated by `options` on `pm`.
        match options.to_lowercase().as_ref() {
            "q" => pm.q(&kws, &flags).await,
            "qc" => pm.qc(&kws, &flags).await,
            "qe" => pm.qe(&kws, &flags).await,
            "qi" => pm.qi(&kws, &flags).await,
            "qii" => pm.qii(&kws, &flags).await,
            "qk" => pm.qk(&kws, &flags).await,
            "ql" => pm.ql(&kws, &flags).await,
            "qm" => pm.qm(&kws, &flags).await,
            "qo" => pm.qo(&kws, &flags).await,
            "qp" => pm.qp(&kws, &flags).await,
            "qs" => pm.qs(&kws, &flags).await,
            "qu" => pm.qu(&kws, &flags).await,
            "r" => pm.r(&kws, &flags).await,
            "rn" => pm.rn(&kws, &flags).await,
            "rns" => pm.rns(&kws, &flags).await,
            "rs" => pm.rs(&kws, &flags).await,
            "rss" => pm.rss(&kws, &flags).await,
            "s" => pm.s(&kws, &flags).await,
            "sc" => pm.sc(&kws, &flags).await,
            "scc" => pm.scc(&kws, &flags).await,
            "sccc" => pm.sccc(&kws, &flags).await,
            "sg" => pm.sg(&kws, &flags).await,
            "si" => pm.si(&kws, &flags).await,
            "sii" => pm.sii(&kws, &flags).await,
            "sl" => pm.sl(&kws, &flags).await,
            "ss" => pm.ss(&kws, &flags).await,
            "su" => pm.su(&kws, &flags).await,
            "suy" => pm.suy(&kws, &flags).await,
            "sw" => pm.sw(&kws, &flags).await,
            "sy" => pm.sy(&kws, &flags).await,
            "u" => pm.u(&kws, &flags).await,
            _ => Err(Error::ArgParseError {
                msg: format!("invalid flag combination `-{options}`"),
            }),
        }
    }
}
