//! Generates the boilerplate code for `Pm`, `MockPm` and `Pacaptr` from the
//! list of supported methods.
//!
//! The generated files are checked into the repository. To regenerate them
//! after changing [`METHODS`] or [`OPS`], run:
//!
//! ```sh
//! SNAPSHOTS=overwrite cargo test --test codegen
//! ```

use std::{env, fmt::Write as _, fs, path::Path};

use itertools::Itertools;

/// The list of [`pacman`](https://wiki.archlinux.org/index.php/Pacman) methods
/// supported by [`pacaptr`](crate), as doc comments. The method name is the
/// lowercased first word of each comment.
// We have to specify the length there (the elision is blocked by https://github.com/rust-lang/rfcs/pull/2545).
// TODO: Fix this when the issue is resolved.
const METHODS: [&str; 31] = [
    "Q generates a list of installed packages.",
    "Qc shows the changelog of a package.",
    "Qe lists packages installed explicitly (not as dependencies).",
    "Qi displays local package information: name, version, description, etc.",
    "Qii displays local packages which require X to be installed, aka local reverse dependencies.",
    "Qk verifies one or more packages.",
    "Ql displays files provided by local package.",
    "Qm lists packages that are installed but are not available in any installation source (anymore).",
    "Qo queries the package which provides FILE.",
    "Qp queries a package supplied through a file supplied on the command line rather than an entry in the package management database.",
    "Qs searches locally installed package for names or descriptions.",
    "Qu lists packages which have an update available.",
    "R removes a single package, leaving all of its dependencies installed.",
    "Rn removes a package and skips the generation of configuration backup files.",
    "Rns removes a package and its dependencies which are not required by any other installed package, and skips the generation of configuration backup files.",
    "Rs removes a package and its dependencies which are not required by any other installed package, and not explicitly installed by the user.",
    "Rss removes a package and its dependencies which are not required by any other installed package.",
    "S installs one or more packages by name.",
    "Sc removes all the cached packages that are not currently installed, and the unused sync database.",
    "Scc removes all files from the cache.",
    "Sccc performs a deeper cleaning of the cache than `Scc` (if applicable).",
    "Sg lists all packages belonging to the GROUP.",
    "Si displays remote package information: name, version, description, etc.",
    "Sii displays packages which require X to be installed, aka reverse dependencies.",
    "Sl displays a list of all packages in all installation sources that are handled by the package management.",
    "Ss searches for package(s) by searching the expression in name, description, short description.",
    "Su updates outdated packages.",
    "Suy refreshes the local package database, then updates outdated packages.",
    "Sw retrieves all packages from the server, but does not install/upgrade anything.",
    "Sy refreshes the local package database.",
    "U upgrades or adds package(s) to the system and installs the required dependencies from sync repositories.",
];

/// Gets the method name from its doc comment.
fn method_name(doc: &str) -> String {
    doc.split_once(' ')
        .expect("doc comment should start with the method name and a space")
        .0
        .to_lowercase()
}

const HEADER: &str = "// @generated by `tests/codegen.rs`, DO NOT EDIT BY HAND.
// Run `SNAPSHOTS=overwrite cargo test --test codegen` to regenerate.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(clippy::too_many_lines)]

";

/// Checks that the file at `rel_path` (relative to the crate root) matches
/// `expected`, or overwrites it if `SNAPSHOTS=overwrite` is set.
fn check(path: impl AsRef<Path>, expected: &str) {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(path);
    if env::var_os("SNAPSHOTS").is_some_and(|s| s.eq_ignore_ascii_case("overwrite")) {
        fs::write(&path, expected).unwrap();
        return;
    }
    let actual = fs::read_to_string(&path).expect("input path should exist and be readable");
    assert_eq!(
        actual,
        expected,
        "`{}` is out of date, run `SNAPSHOTS=overwrite cargo test --test codegen` to regenerate",
        path.display(),
    );
}

#[test]
fn gen_pm_imp() {
    let mut out = String::from(HEADER);
    out.push_str(
        r"use async_trait::async_trait;

use super::BoxPm;
use crate::{config::Config, error::{Error, Result}};

/// The feature set of a Package Manager defined by `pacman` commands.
///
/// For method explanation see:
/// - <https://wiki.archlinux.org/index.php/Pacman>
/// - <https://wiki.archlinux.org/index.php/Pacman/Rosetta>
#[async_trait]
pub trait Pm: Sync {
    /// Gets the name of the package manager.
    fn name(&self) -> &str;

    /// Gets the config of the package manager.
    fn cfg(&self) -> &Config;

    /// Wraps the [`Pm`] instance in a [`Box`].
    fn boxed<'a>(self) -> BoxPm<'a>
    where
        Self: Sized + Send + 'a,
    {
        Box::new(self)
    }
",
    );

    for doc in METHODS {
        let name = method_name(doc);
        _ = writeln!(
            out,
            r#"
    /// {doc}
    async fn {name}(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {{
        Err(Error::OperationUnimplementedError {{
            op: "{name}".into(),
            pm: self.name().into(),
        }})
    }}"#,
        );
    }
    _ = writeln!(out, "\n}}");

    check("src/pm/imp.rs", &out);
}

#[test]
fn gen_pm_tests() {
    let mut out = String::from(HEADER);
    out.push_str(
        r#"#![allow(missing_docs)]

use super::*;
use crate::config::Config;

#[derive(Debug)]
pub struct MockPm {
    pub cfg: Config,
}

#[async_trait]
impl Pm for MockPm {
    fn name(&self) -> &'static str { "mockpm" }
    fn cfg(&self) -> &Config { &self.cfg }
"#,
    );
    for name in METHODS.into_iter().map(method_name) {
        _ = writeln!(
            out,
            r#"
    async fn {name}(&self, kws: &[&str], flags: &[&str]) -> Result<()> {{
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: {name} {{kws:?}}")
    }}"#
        );
    }
    _ = writeln!(out, "}}");

    check("src/pm/tests.rs", &out);
}

#[test]
#[allow(clippy::too_many_lines)]
fn gen_cmd_imp() {
    /// An operation (a variant of `Operations`) to be collected.
    struct Op<'a> {
        /// The name of the variant.
        name: &'a str,
        /// The boolean flags that enable `dry_run` when set.
        ///
        /// The [`str`] here is used as a collection of [`char`]s.
        dry_run: &'a str,
        /// The flags repeated in the method name once per occurrence.
        ///
        /// The [`str`] here is used as a collection of [`char`]s.
        counted: &'a str,
    }

    impl Op<'_> {
        const ALL: [Self; 4] = [
            Self {
                name: "Query",
                dry_run: "",
                counted: "ceiklmopsu",
            },
            Self {
                name: "Remove",
                dry_run: "p",
                counted: "ns",
            },
            Self {
                name: "Sync",
                dry_run: "p",
                counted: "cgilsuwy",
            },
            Self {
                name: "Update",
                dry_run: "p",
                counted: "",
            },
        ];
    }

    let mut out = String::from(HEADER);
    out.push_str(
        r#"use std::iter;

use itertools::Itertools;
use pacaptr::{
    config::Config,
    error::{Error, Result},
    pm::BoxPm,
    print::{println, prompt},
};

use super::{Operations, Pacaptr};

impl Pacaptr {
    /// Executes the job according to the flags received and the package manager
    /// detected.
    ///
    /// # Errors
    /// See [`Error`](pacaptr::error::Error) for a list of possible errors.
    #[allow(trivial_numeric_casts)]
    pub(super) async fn dispatch_from(&self, mut cfg: Config) -> Result<()> {
        // Collect options as a `String`, eg. `-S -y -u => "Suy"`.
        //
        // In `Pm` we ensure the Pacman methods are all named with flags in
        // ASCII order, eg. `Suy` instead of `Syu`. Then, in order to
        // stay coherent with Rust coding style the method name should be
        // `suy`.
        let mut options = String::new();
        match self.ops {
"#,
    );
    for Op {
        name: op,
        dry_run,
        counted,
    } in Op::ALL
    {
        // The first letter of the operation name is exactly its short flag.
        let initial = &op[..1];
        let fields = dry_run.chars().chain(counted.chars()).format(", ");
        _ = writeln!(
            out,
            r"            Operations::{op} {{ {fields}, .. }} => {{
                options.push('{initial}');"
        );
        for flag in dry_run.chars() {
            _ = writeln!(out, "                if {flag} {{ cfg.dry_run = true; }}");
        }
        for flag in counted.chars() {
            _ = writeln!(
                out,
                "                options.extend(iter::repeat_n({flag:?}, usize::from({flag})));"
            );
        }
        _ = writeln!(out, "            }}");
    }
    out.push_str(
        r"        }
        let options = String::from_iter(options.chars().sorted_unstable());

        // Ensure that the cursor is not hidden when `Ctrl-C` is used.
        // See: https://github.com/console-rs/dialoguer/issues/77#issuecomment-669986406
        if let Err(e) = ctrlc::set_handler(move || {
            let term = console::Term::stdout();
            _ = term.show_cursor();
        }) {
            println(&*prompt::INFO, e);
        }

        let pm = BoxPm::from(cfg);

        let kws = self.keywords.iter().map(AsRef::as_ref).collect_vec();
        let flags = self.extra_flags.iter().map(AsRef::as_ref).collect_vec();

        // Call the method indicated by `options` on `pm`.
        match options.to_lowercase().as_ref() {
",
    );
    for name in METHODS.into_iter().map(method_name) {
        _ = writeln!(
            out,
            r#"            "{name}" => pm.{name}(&kws, &flags).await,"#
        );
    }
    out.push_str(
        r#"            _ => Err(Error::ArgParseError {
                msg: format!("invalid flag combination `-{options}`"),
            }),
        }
    }
}
"#,
    );

    check("src/cmd/imp.rs", &out);
}
