[package]
name = "pacaptr-macros"
version.workspace = true
license.workspace = true
edition.workspace = true

homepage = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
repository = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
description = "Implementation of several macros used in pacaptr."

[lib]
proc-macro = true

[dependencies]
itertools = { workspace = true }
litrs = "1.0.0"
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = "3.0.3"

[lints]
workspace = true
