// @generated by `tests/codegen.rs`, DO NOT EDIT BY HAND.
// Run `SNAPSHOTS=overwrite cargo test --test codegen` to regenerate.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(clippy::too_many_lines)]

use async_trait::async_trait;

use super::BoxPm;
use crate::{config::Config, error::{Error, Result}};

/// The feature set of a Package Manager defined by `pacman` commands.
///
/// For method explanation see:
/// - <https://wiki.archlinux.org/index.php/Pacman>
/// - <https://wiki.archlinux.org/index.php/Pacman/Rosetta>
#[async_trait]
pub trait Pm: Sync {
    /// Gets the name of the package manager.
    fn name(&self) -> &str;

    /// Gets the config of the package manager.
    fn cfg(&self) -> &Config;

    /// Wraps the [`Pm`] instance in a [`Box`].
    fn boxed<'a>(self) -> BoxPm<'a>
    where
        Self: Sized + Send + 'a,
    {
        Box::new(self)
    }

    /// Q generates a list of installed packages.
    async fn q(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "q".into(),
            pm: self.name().into(),
        })
    }

    /// Qc shows the changelog of a package.
    async fn qc(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qc".into(),
            pm: self.name().into(),
        })
    }

    /// Qe lists packages installed explicitly (not as dependencies).
    async fn qe(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qe".into(),
            pm: self.name().into(),
        })
    }

    /// Qi displays local package information: name, version, description, etc.
    async fn qi(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qi".into(),
            pm: self.name().into(),
        })
    }

    /// Qii displays local packages which require X to be installed, aka local reverse dependencies.
    async fn qii(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qii".into(),
            pm: self.name().into(),
        })
    }

    /// Qk verifies one or more packages.
    async fn qk(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qk".into(),
            pm: self.name().into(),
        })
    }

    /// Ql displays files provided by local package.
    async fn ql(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "ql".into(),
            pm: self.name().into(),
        })
    }

    /// Qm lists packages that are installed but are not available in any installation source (anymore).
    async fn qm(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qm".into(),
            pm: self.name().into(),
        })
    }

    /// Qo queries the package which provides FILE.
    async fn qo(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qo".into(),
            pm: self.name().into(),
        })
    }

    /// Qp queries a package supplied through a file supplied on the command line rather than an entry in the package management database.
    async fn qp(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qp".into(),
            pm: self.name().into(),
        })
    }

    /// Qs searches locally installed package for names or descriptions.
    async fn qs(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qs".into(),
            pm: self.name().into(),
        })
    }

    /// Qu lists packages which have an update available.
    async fn qu(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "qu".into(),
            pm: self.name().into(),
        })
    }

    /// R removes a single package, leaving all of its dependencies installed.
    async fn r(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "r".into(),
            pm: self.name().into(),
        })
    }

    /// Rn removes a package and skips the generation of configuration backup files.
    async fn rn(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "rn".into(),
            pm: self.name().into(),
        })
    }

    /// Rns removes a package and its dependencies which are not required by any other installed package, and skips the generation of configuration backup files.
    async fn rns(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "rns".into(),
            pm: self.name().into(),
        })
    }

    /// Rs removes a package and its dependencies which are not required by any other installed package, and not explicitly installed by the user.
    async fn rs(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "rs".into(),
            pm: self.name().into(),
        })
    }

    /// Rss removes a package and its dependencies which are not required by any other installed package.
    async fn rss(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "rss".into(),
            pm: self.name().into(),
        })
    }

    /// S installs one or more packages by name.
    async fn s(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "s".into(),
            pm: self.name().into(),
        })
    }

    /// Sc removes all the cached packages that are not currently installed, and the unused sync database.
    async fn sc(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "sc".into(),
            pm: self.name().into(),
        })
    }

    /// Scc removes all files from the cache.
    async fn scc(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "scc".into(),
            pm: self.name().into(),
        })
    }

    /// Sccc performs a deeper cleaning of the cache than `Scc` (if applicable).
    async fn sccc(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "sccc".into(),
            pm: self.name().into(),
        })
    }

    /// Sg lists all packages belonging to the GROUP.
    async fn sg(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "sg".into(),
            pm: self.name().into(),
        })
    }

    /// Si displays remote package information: name, version, description, etc.
    async fn si(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "si".into(),
            pm: self.name().into(),
        })
    }

    /// Sii displays packages which require X to be installed, aka reverse dependencies.
    async fn sii(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "sii".into(),
            pm: self.name().into(),
        })
    }

    /// Sl displays a list of all packages in all installation sources that are handled by the package management.
    async fn sl(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "sl".into(),
            pm: self.name().into(),
        })
    }

    /// Ss searches for package(s) by searching the expression in name, description, short description.
    async fn ss(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "ss".into(),
            pm: self.name().into(),
        })
    }

    /// Su updates outdated packages.
    async fn su(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "su".into(),
            pm: self.name().into(),
        })
    }

    /// Suy refreshes the local package database, then updates outdated packages.
    async fn suy(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "suy".into(),
            pm: self.name().into(),
        })
    }

    /// Sw retrieves all packages from the server, but does not install/upgrade anything.
    async fn sw(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "sw".into(),
            pm: self.name().into(),
        })
    }

    /// Sy refreshes the local package database.
    async fn sy(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "sy".into(),
            pm: self.name().into(),
        })
    }

    /// U upgrades or adds package(s) to the system and installs the required dependencies from sync repositories.
    async fn u(&self, _kws: &[&str], _flags: &[&str]) -> Result<()> {
        Err(Error::OperationUnimplementedError {
            op: "u".into(),
            pm: self.name().into(),
        })
    }

}
