// @generated by `tests/codegen.rs`, DO NOT EDIT BY HAND.
// Run `SNAPSHOTS=overwrite cargo test --test codegen` to regenerate.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(clippy::too_many_lines)]

#![allow(missing_docs)]

use super::*;
use crate::config::Config;

#[derive(Debug)]
pub struct MockPm {
    pub cfg: Config,
}

#[async_trait]
impl Pm for MockPm {
    fn name(&self) -> &'static str { "mockpm" }
    fn cfg(&self) -> &Config { &self.cfg }

    async fn q(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: q {kws:?}")
    }

    async fn qc(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qc {kws:?}")
    }

    async fn qe(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qe {kws:?}")
    }

    async fn qi(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qi {kws:?}")
    }

    async fn qii(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qii {kws:?}")
    }

    async fn qk(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qk {kws:?}")
    }

    async fn ql(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: ql {kws:?}")
    }

    async fn qm(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qm {kws:?}")
    }

    async fn qo(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qo {kws:?}")
    }

    async fn qp(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qp {kws:?}")
    }

    async fn qs(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qs {kws:?}")
    }

    async fn qu(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: qu {kws:?}")
    }

    async fn r(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: r {kws:?}")
    }

    async fn rn(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: rn {kws:?}")
    }

    async fn rns(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: rns {kws:?}")
    }

    async fn rs(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: rs {kws:?}")
    }

    async fn rss(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: rss {kws:?}")
    }

    async fn s(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: s {kws:?}")
    }

    async fn sc(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: sc {kws:?}")
    }

    async fn scc(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: scc {kws:?}")
    }

    async fn sccc(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: sccc {kws:?}")
    }

    async fn sg(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: sg {kws:?}")
    }

    async fn si(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: si {kws:?}")
    }

    async fn sii(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: sii {kws:?}")
    }

    async fn sl(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: sl {kws:?}")
    }

    async fn ss(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: ss {kws:?}")
    }

    async fn su(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: su {kws:?}")
    }

    async fn suy(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: suy {kws:?}")
    }

    async fn sw(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: sw {kws:?}")
    }

    async fn sy(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: sy {kws:?}")
    }

    async fn u(&self, kws: &[&str], flags: &[&str]) -> Result<()> {
        let kws = itertools::chain!(kws, flags).collect_vec();
        panic!("should run: u {kws:?}")
    }
}
